# Generated by Django 5.2.11 on 2026-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
