# Generated by Django 5.2.11 on 2026-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
